services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true
    shm_size: "256mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: "host"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS="*"
    volumes:
      - ollama_storage:/root/.ollama
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui
    volumes:
      - open_webui_storage:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
    depends_on:
      - ollama
    restart: always

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    environment:
      - JELLYFIN_PublishedServerUrl=http://<IP_ADDRESS>
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - <PATH_TO>:/media/movies:ro
      - <PATH_TO>:/media/shows:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped

volumes:
  ollama_storage:
  open_webui_storage:
